<?php

$links = [
 ["Scientists For Wired Technology"=>"https://scientists4wiredtech.com/"],
 ["5G Appeal"=>"https://www.researchgate.net/profile/Elizabeth_Kelley6/publication/298533689_International_Appeal_Scientists_call_for_protection_from_non-ionizing_electromagnetic_field_exposure/links/56e9c66208ae25ede830c535/International-Appeal-Scientists-call-for-protection-from-non-ionizing-electromagnetic-field-exposure.pdf"],
 ["Cellular phone Brain Tumor Risk"=>"https://www.ncbi.nlm.nih.gov/pubmed/20483835"],
 ["Breast Cancer & Cell Phones"=>"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3789302/"],
 ["Is 5G Harmful to Our Health?"=>"https://www.saferemr.com/2017/09/5g-wireless-technology-is-5g-harmful-to.html"],
 ["5G Dr Joel Moskowitz Daily Mail Article"=>"https://www.dailymail.co.uk/health/article-5784487/The-roll-5G-wireless-service-massive-health-experiment-public-health-expert-warns-a.html"],
 ["Letters From 250 Scientists From 35 Countries On The Health Risk Of 5G"=>"https://ehtrust.org/small-cells-mini-cell-towers-health-letters-scientists-health-risk-5g/"],
 ["5G Letter by 18 Doctors &amp; Scientists to California Gov."=>"https://ehtrust.org/wp-content/uploads/Lennart-Hardell-BROWN-HONORABLE-EDMUND-G.pdf"],
 ["5G Letter From Dr. Yael Stein MD To FCC"=>"https://ehtrust.org/letter-fcc-dr-yael-stein-md-opposition-5g-spectrum-frontiers/"],
 ["5G wireless expansion: Public health implications"=>"https://www.sciencedirect.com/science/article/pii/S0013935118300161"],
 ["Dr. Leszczynski Sounds 5G Warning"=>"https://mdsafetech.org/2018/07/18/dr-leszczynski-sounds-warning-at-australian-meeting-precaution-with-5g/"],
 ["Bioinitiative Report"=>"http://www.bioinitiative.org/table-of-contents/"],
 ["Oxidative Damage to Mitochondrial DNA"=>"https://www.beyotime.com/reference/s0033-43-a0216-ref10.pdf"],
 ["Cell usage linked to Male Infertility"=>"https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006446"],
 ["Influence of cell towers proxy...& cancer"=>"http://www.tetrawatch.net/papers/naila.pdf"],
 ["Animal study finds cancer"=>"https://ehtrust.org/worlds-largest-animal-study-on-cell-tower-radiation-confirms-cancer-link/"],
 ["Rat Study"=>"https://www.sciencedirect.com/science/article/abs/pii/S0013935118300367"],
 ["7 WiFi threats to human health"=>"https://www.sciencedirect.com/science/article/pii/S0013935118300355"],
 ["Public Heath Implications"=>"https://www.pathophysiologyjournal.com/article/S0928-4680(09)00017-0/fulltext"],
 ["Cordless/cell phone cancer risk"=>"https://www.pathophysiologyjournal.com/article/S0928-4680(12)00110-1/fulltext"],
 ["EMF playing with fire"=>"https://www.aaemonline.org/emf_rf_position.php"],
 ["Bio-logical effect from Smart Meters"=>"https://www.aaemonline.org/pdf/pressadvisoryemf.pdf"],
 ["PubMed.gov - Brain Tumors Diagnosed"=>"https://www.ncbi.nlm.nih.gov/pubmed/16541280"],
 ["World Health Organization Findings"=>"https://www.iarc.fr/wp-content/uploads/2018/07/pr208_E.pdf"],
 ["Children & Cell phones"=>"https://microwavenews.com/children.adults.html"],
 ["Brain Tumors Found"=>"https://microwavenews.com/news-center/gbm-frontal-and-tempral-lobes"],
 ["EMF Safety Research"=>"https://www.saferemr.com/"],
 ["Cellular Death in Flies"=>"https://www.tandfonline.com/doi/full/10.3109/15368378.2014.971959"],
 ["Insect Cell Death"=>"https://www.ncbi.nlm.nih.gov/pubmed/23781995"],
 ["More Insect Cell Death"=>"https://www.tandfonline.com/doi/abs/10.1081/JBC-120039350"],
 ["Studies of Cell Phone Radiation"=>"https://www.biorxiv.org/content/biorxiv/early/2016/05/26/055699.full.pdf"]
];